# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export 
NULL

#' Principal Component Analysis
#' @param data_mat numeric data matrix [n x p]
#' @param num_components int desired number of components
#' @importFrom Rcpp evalCpp
#' @returns Lower dimension representation of input matrix  [n x num_components]
#' @export
PCA_interface <- function(data_mat, num_components) {
    .Call('_PCAPackage_PCA_interface', PACKAGE = 'PCAPackage', data_mat, num_components)
}

